## AULA 20 - Criação de vetores e arrays e numpy.random


In [ ]:
import numpy as np

In [ ]:
minha_lista = [1,2,3]

In [ ]:
minha_lista

[1, 2, 3]

In [ ]:
np.array(minha_lista)

array([1, 2, 3])

In [ ]:
minha_matriz = [[1,2,3],[4,5,6],[7,8,9]]

In [ ]:
# o número de '[[' é a dimensão da estrutura
np.array(minha_matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
 # não inclui o ultimo elemento
 np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# formato np.arange(start, end, step)
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [ ]:
mtz = np.zeros((5,5))

In [ ]:
print(mtz)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [ ]:
print(np.ones((2,2)))


[[1. 1.]
 [1. 1.]]


In [ ]:
print(np.eye(4))


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
np.random.rand(5)

array([0.43926056, 0.67714046, 0.93257377, 0.4997725 , 0.24863676])

In [ ]:
mtz.reshape((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
mtz.shape

(5, 5)

In [ ]:

mtz.max()

0.0

In [ ]:

mtz.min()

0.0

In [ ]:
mtz.argmax()

0

In [ ]:
mtz.argmin()

0

## AULA 21- Indexação e Fatiamento de arrays

In [ ]:
print(mtz[2:4])

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
print(mtz[2:])

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
print(mtz[:3])

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
arr2 = mtz[:3]

In [ ]:
print(mtz[2:][:2])

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
print("=======================")
print("Matriz mtz")
print(mtz)
print("=======================")
print("Matriz arr2")
print(arr2)

Matriz mtz
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Matriz arr2
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
arr3 = mtz[:2].copy()

In [ ]:
print(arr3)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
bol = arr3 == 0
arr3[bol]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
arr2[0:2, 2]

array([0., 0.])

## Aula 22 - Operações com Numpy Arrays


In [ ]:
vet = np.arange(0,16)
print(vet)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [ ]:
vet/vet

<ipython-input-40-12b4575ed4e1>:1: RuntimeWarning: invalid value encountered in divide
  vet/vet


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.])

In [ ]:
print(vet*vet)

[  0   1   4   9  16  25  36  49  64  81 100 121 144 169 196 225]


In [ ]:
1/0

ZeroDivisionError: division by zero

In [ ]:
vet**3

[   0    1    8   27   64  125  216  343  512  729 1000 1331 1728 2197
 2744 3375]


In [ ]:
vet+100

[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115]


In [ ]:
vet*vet

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225])

In [ ]:
np.sqrt(vet)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335])

In [ ]:
np.exp(vet)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06])

In [ ]:
np.mean(vet)

7.5

In [ ]:
np.std(vet)

4.6097722286464435

In [ ]:
np.sin(vet)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784])

In [ ]:
np.max(vet)

15

## Exercícios Propostos


In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [ ]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [ ]:
arr = np.arange(10, 51, 2)

In [ ]:
result = np.array(list(filter(lambda x: x % 2 == 0, arr)))

print(result)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]
